import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata = {
  title: "Omar.dev",
  description: "Generated by create next app",
  icons: {
    icon: "./logo.ico",
  },
};

git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/omarbenaroua/omar.dev   
git push -u origin main

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
